name: Prerelease

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push Docker image
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        docker build -t myapp:dev .
        docker tag myapp:dev your-nexus-repo-url/dev/myapp:latest
        docker login -u $NEXUS_USERNAME -p $NEXUS_PASSWORD your-nexus-repo-url
        docker push your-nexus-repo-url/dev/myapp:latest
